version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth_service
    ports:
      - "5443:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  my-go-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
